config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup',
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
    }
  namespace :api do
    namespace :v1 do
      resources :user_images do
        collection do
          post :send_image
          post :claim_image
        end
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
	include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylist'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable,
       :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  has_many :user_images, dependent: :destroy
end

app/models/user_image.rb
class UserImage < ApplicationRecord
	has_one_attached :pic
	belongs_to :user
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  before_action :authenticate_user!


end

app/controllers/api/v1/user_images_controller.rb
class Api::V1::UserImagesController < Api::V1::BaseController
  before_action :set_user_image, only: %i[ show send_image claim_image]

  def index
    @user_images = current_user.user_images.all
    render json: {success: true, message: "All Images", data: @user_images.collect {|image| user_image(image)}}
  end

  def show
    render json: {success: true, message: "Single Image", data: @user_image.attributes.merge(image: @user_image.pic.attached? ? url_for(@user_image.pic) : '')}
  end

  def create
    @user_image = current_user.user_images.new(user_image_params)
    @user_image.uuid = SecureRandom.uuid
      if @user_image.save
        render json: {success: true, message: "Image created successfully", data: @user_image.attributes.merge(image: @user_image.pic.attached? ?  url_for(@user_image.pic) : '')}
      end
  end

  def send_image
    if @user_image.present? && params[:email].present?
      client = Customerio::APIClient.new('804b58df7d21727da911cd607e7d7c86', region: Customerio::Regions::US)
      request = Customerio::SendEmailRequest.new(
        to: params[:email],
        from: 'team@womboapp.com',
        subject: 'Image link',
        body: "nftmaker://147.182.199.116/api/v1/user_images/#{@user_image.uuid}"
      )
      begin
        response = client.send_email(request)
        if response.code == '200'
          render json: 'image sent'
        end
      rescue Customerio::InvalidResponse => e
        puts e.code, e.message
      end
    end
  end

  def claim_image
    if @user_image.status == false
      if @user_image && @user_image.user_id.present?
        @user_image.update(user_id: @user_image.user.id, status: true)
        render json: {success: true, message: "Image claimed successfully", data: @user_image.attributes.merge(image: @user_image.pic.attached? ?  url_for(@user_image.pic) : '')}
      else
        render json: {success: false, message: "Image not present"}
      end
    else
      render json: {success: false, message: "You have already claimed", data: @user_image.attributes.merge(image: @user_image.pic.attached? ?  url_for(@user_image.pic) : '')}
    end
  end

  private
    def set_user_image
      @user_image = UserImage.find_by(uuid: params[:uuid])
    end

    def user_images
      @user_image = UserImage.find_by(uuid: params[:uuid])
    end

    def user_image_params
      params.require(:user_image).permit(:name, :pic)
    end

    def user_image(image)
      image.attributes.merge(image: image.pic.attached? ?  url_for(image.pic) : '')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  include Response
  include ExceptionHandler

  def render_resource(resource)
    if resource.errors.empty?
      @user_response = resource.attributes
      json_response(@user_response, message = params[:controller].eql?('users/registrations') ? 'signed up successfully' : 'login successfully')
    else
      json_error_response(resource.errors, params[:controller].eql?('users/registrations') ? 'signup failed' :  'login failed', :bad_request)
    end
  end

  def authenticate_user!
    render json: {success: false, message: "need to sign in or sign up before continuing", status: 401} unless current_user.present?
    # render json: "need to sign in or sign up before continuing", status: 401
  end

end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
    # provides the more graceful `included` method
    extend ActiveSupport::Concern
  
    included do
      rescue_from ActiveRecord::RecordNotFound do |e|
        json_response({ message: e.message }, :not_found)
      end
  
      rescue_from ActiveRecord::RecordInvalid do |e|
        json_response({ message: e.message }, :unprocessable_entity)
      end
    end
  end

app/controllers/concerns/response.rb
module Response
  def json_response(object, message = "", status)
    if status.eql?(:not_found)
      status = status
    else
      status = :ok
    end
    response = {
          "status": Rack::Utils.status_code(status),
        "message": message,
        "data": object
      }
    render json: response, status: status

  end

  def json_error_response(errors, message, status)
      response = {
          "status": Rack::Utils.status_code(status),
        "message": message,
        "errors": errors
      }

    render json: response, status: status
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json
  
  def create
    return render json: 'please enter params in good format' if params[:user].nil?
    build_resource(sign_up_params)
    resource.save
    unless resource.errors.any?
      sign_in(resource_name, resource)
      render_resource(resource)
    else
      puts resource.errors.full_messages
      render_resource(resource)
    end
  end

  protected

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :phone_no)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    return render json: {success: false, message: "Invalid email of password", status: 401} if resource.new_record?
    render_resource(resource)
  end

  def respond_to_on_destroy
    head :ok
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImagesTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_images/_form.html.erb
<%= form_with(model: user_image, local: true) do |form| %>
  <% if user_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_image.errors.count, "error") %> prohibited this user_image from being saved:</h2>

      <ul>
      <% user_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_images/edit.html.erb
<h1>Editing User Image</h1>

<%= render 'form', user_image: @user_image %>

<%= link_to 'Show', @user_image %> |
<%= link_to 'Back', user_images_path %>

app/views/user_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_images.each do |user_image| %>
      <tr>
        <td><%= user_image.name %></td>
        <td><%= link_to 'Show', user_image %></td>
        <td><%= link_to 'Edit', edit_user_image_path(user_image) %></td>
        <td><%= link_to 'Destroy', user_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Image', new_user_image_path %>

app/views/user_images/new.html.erb
<h1>New User Image</h1>

<%= render 'form', user_image: @user_image %>

<%= link_to 'Back', user_images_path %>

app/views/user_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_image.name %>
</p>

<%= link_to 'Edit', edit_user_image_path(@user_image) %> |
<%= link_to 'Back', user_images_path %>